dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgflags-dev
            - libgoogle-glog-dev
            - libgtest-dev
            - libssl-dev
            - swig3.0
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libgflags-dev
            - libgoogle-glog-dev
            - libgtest-dev
            - libssl-dev
            - swig3.0
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libgflags-dev
            - libgoogle-glog-dev
            - libgtest-dev
            - libssl-dev
            - swig3.0
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7
            - libgflags-dev
            - libgoogle-glog-dev
            - libgtest-dev
            - libssl-dev
            - swig3.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - ${CC} --version
  - ${CXX} --version

script:
  - mkdir build
  - cd build
  - cmake -DGTEST_ROOT=/usr/src/gtest -DWITH_GFLAGS=ON -DWITH_GLOG=ON ..
  - make && make test
